name: flutter_storage
description: App Database

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.4.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  rxdart: ^0.27.3
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
